/**
 * unit-test/delivery/pr-delivery.ts - 创建新 PR 交付（P1）
 *
 * 对应迭代四 §2.6 方式三「Create PR with unit tests」。
 *
 * 实现概要:
 *   1. 从当前 PR 分支 (input.branch) 创建新分支 add-tests/pr-<n>
 *   2. 在新分支上写入每个测试文件（复用 commitDelivery 的"按文件提交"逻辑）
 *   3. 调用 pulls.create 创建新 PR，base = 原 PR 的 head 分支
 *   4. 返回新 PR url
 *
 * 失败处理:
 * - 任意一步失败 → 在 outcome.errors 记录，并 best-effort 继续后续目标
 *
 * 权限要求:
 * - GITHUB_TOKEN 需要 `contents: write` + `pull-requests: write`
 */
import {info, warning} from '@actions/core'
import {octokit} from '../../octokit'
import type {DeliveryInput, DeliveryOutcome} from '../types'

export async function prDelivery(
  input: DeliveryInput
): Promise<DeliveryOutcome> {
  const outcome: DeliveryOutcome = {
    mode: 'pr',
    succeeded: 0,
    errors: []
  }

  if (!input.branch) {
    outcome.errors.push('未指定源分支')
    return outcome
  }

  const newBranch = `add-tests/pr-${input.prNumber}-${Date.now()}`
  try {
    // 1. 从源分支创建新分支
    const refRes = await octokit.git.getRef({
      owner: input.owner,
      repo: input.repo,
      ref: `heads/${input.branch}`
    })
    await octokit.git.createRef({
      owner: input.owner,
      repo: input.repo,
      ref: `refs/heads/${newBranch}`,
      sha: refRes.data.object.sha
    })
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    outcome.errors.push(`无法创建新分支 ${newBranch}: ${msg}`)
    return outcome
  }

  // 2. 提交文件到新分支
  for (const test of input.run.tests) {
    if (!test.passedStaticCheck) {
      outcome.errors.push(
        `${test.target.name} 未通过静态校验，跳过提交: ${test.staticCheckError}`
      )
      continue
    }
    try {
      await octokit.repos.createOrUpdateFileContents({
        owner: input.owner,
        repo: input.repo,
        path: test.suggestedTestPath,
        message: `test: add unit tests for ${test.target.name}`,
        content: Buffer.from(test.code, 'utf-8').toString('base64'),
        branch: newBranch
      })
      outcome.succeeded += 1
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e)
      warning(`unit-test/pr-delivery: commit failed: ${msg}`)
      outcome.errors.push(`${test.suggestedTestPath}: ${msg}`)
    }
  }

  if (outcome.succeeded === 0) {
    outcome.errors.push('无可提交的测试文件，已放弃创建 PR')
    await deleteBranchSafe(input.owner, input.repo, newBranch)
    return outcome
  }

  // 3. 创建新 PR
  try {
    const pr = await octokit.pulls.create({
      owner: input.owner,
      repo: input.repo,
      title: `test: add unit tests for PR #${input.prNumber} changes`,
      body: prBodyFor(input),
      head: newBranch,
      base: input.branch
    })
    outcome.newPrUrl = pr.data.html_url
    info(`unit-test/pr-delivery: created PR: ${pr.data.html_url}`)
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e)
    outcome.errors.push(`创建 PR 失败: ${msg}`)
    // 创建 PR 失败 → 分支已 commit 但不再有归宿，清理避免垃圾
    await deleteBranchSafe(input.owner, input.repo, newBranch)
  }

  return outcome
}

/** best-effort 删除残留分支，失败不阻塞主流程 */
async function deleteBranchSafe(
  owner: string,
  repo: string,
  branch: string
): Promise<void> {
  try {
    await octokit.git.deleteRef({owner, repo, ref: `heads/${branch}`})
    info(`unit-test/pr-delivery: cleaned up branch ${branch}`)
  } catch (e) {
    warning(
      `unit-test/pr-delivery: failed to delete branch ${branch}: ${
        e instanceof Error ? e.message : String(e)
      }`
    )
  }
}

function prBodyFor(input: DeliveryInput): string {
  const lines: string[] = []
  lines.push(`Auto-generated unit tests for changes introduced by #${input.prNumber}.`)
  lines.push('')
  lines.push('| Target | Test file | Cases |')
  lines.push('| :--- | :--- | ---: |')
  for (const t of input.run.tests) {
    lines.push(
      `| \`${t.target.name}\` | \`${t.suggestedTestPath}\` | ${t.caseCount} |`
    )
  }
  lines.push('')
  lines.push(`> 🤖 Generated by AI Reviewer · iteration 4 (unit-test).`)
  return lines.join('\n')
}
